---
title: "Protecting me from myself: Autoantibodies"
author: "Kevin Y. Rono"
output:
  word_document: default
  pdf_document: default
  html_document: default
---

**Loading Limma**
```{r}
if (!require("BiocManager", quietly = TRUE))
  install.packages("BiocManager")

BiocManager::install("limma")

library(limma)
```

**Loading Files**
```{r}

# Store file names

files <- c(".grp", ...)

files2 <- c(".gpr", ...) # second file has an error


# Store directory paths

path <- "/directory1"
path2 <- "/directory2"


# Debugging attempts

columns <- list(R  = "GenePix:F635 Mean", G  = "GenePix:F532 Mean", Rb = "GenePix:B635 Median", Gb = "GenePix:B532 Median")
scan(".gpr", nlines = 1, what = "c", sep = "\t", skip=34)

```


**Loading Data**
```{r}
# Read data
RG <- read.maimages(files2, source="genepix", path=path2)

# Check to see if the genes component has been set.
names(RG$genes)

# Read GAL file
RG$genes <- readGAL(".gal") # gal file
RG$genes[1:30,]

RG$printer <- getLayout(RG$genes)

```

**Image plots**
```{r}
# It is interesting to look at the variation of background values over the array. Consider image plots of the red and green background for the first array
?imageplot()
imageplot(log2(RG$Rb[,1]), RG$printer, low="white", high="red")
imageplot(log2(RG$Gb[,1]), RG$printer, low="white", high="green")

length(log2(RG$Rb[,1])) # 48,386
length(RG$printer) # 6*4*66*32 = 50,688


# Image plot of the un-normalized log-ratios or M-values for the first array:
MA <- normalizeWithinArrays(RG, method="none")
imageplot(MA$M[,1], RG$printer, zlim=c(-3,3))
```

**MA Plots**
```{r}
# MA-plot plots the log-ratio of R vs G against the overall intensity of each spot.
plotMD(MA)

# Now we plot the individual MA-plots for each of the print-tip groups on this array, together with the loess curves which will be used for normalization
plotPrintTipLoess(MA)

# Normalization. 

# Print-tip loess normalization:
MA <- normalizeWithinArrays(RG)
plotPrintTipLoess(MA)

# The following plot shows overall boxplots of the M-values for the four arrays
boxplot(MA$M~col(MA$M),names=colnames(MA$M))

# scale normalize between the arrays
MA <- normalizeBetweenArrays(MA,method="scale")
boxplot(MA$M~col(MA$M),names=colnames(MA$M))
```

**Linear Model**
```{r}
# First setup an appropriate design matrix. The negative numbers in the design matrix indicate the dye-swaps
design <- modelMatrix(targets, ref="wild type")
design

# Now fit a simple linear model for each gene. This has the effect of estimating the average M-value for each gene, adjusting for the dye-swaps.
fit <- lmFit(MA,design)
fit

# Ordinary t-statistics for comparing mutant to wt could be computed by
ordinary.t <- fit$coef / fit$stdev.unscaled / fit$sigma

# We prefer though to use empirical Bayes moderated t-statistics which are computed below.
# Now create an mean difference plot displaying the log-fold-changes and average A-values for each gene.
plotMD(fit)
abline(0,0,col="blue")
```

**Empirical Bayes analysis**
```{r}
# We will now go on and compute empirical Bayes statistics for differential expression. The moderated t-statistics use sample standard deviations which have been squeezed towards a pooled standard deviation value.
fit <- eBayes(fit)
qqt(fit$t,df=fit$df.prior+fit$df.residual,pch=16,cex=0.2)
abline(0,1)

plotMD(fit)
top30 <- order(fit$lods,decreasing=TRUE)[1:30]
text(fit$Amean[top30],fit$coef[top30],labels=fit$genes[top30,"Name"],cex=0.8,col="blue")
```

